# Generated by Django 3.2.8 on 2021-11-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=70)),
                ('jumlah_barang', models.CharField(max_length=70)),
                ('harga_barang', models.CharField(max_length=20)),
            ],
        ),
    ]
